apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-server-v2
  namespace: ab-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-web-server
      version: v2
  template:
    metadata:
      labels:
        app: go-web-server
        version: v2
    spec:
      containers:
        - name: go-web-server
          image: ghcr.io/clep-alexandru/web_go_application:fb1de790bdcd58ce70c1f8f5473a371bb5e6b54c
          envFrom:
            - configMapRef:
                name: go-web-server-config
          ports:
            - containerPort: 8080
