apiVersion: v1
kind: Service
metadata:
  name: go-web-server
  namespace: canary-deployment
spec:
  type: NodePort
  selector:
    app: go-web-server
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080     
