apiVersion: v1
kind: Service
metadata:
  name: go-web-server-preview
  namespace: bluegreen
spec:
  type: NodePort
  selector:
    app: go-web-server
  ports:
  - name: http
    port: 80
    targetPort: 8081
    nodePort: 30081  
