name: CI/CD - Test, Build, Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install sqlmock dependency
        run: go get github.com/DATA-DOG/go-sqlmock

      - name: Run Tests
        run: go test ./...

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/clep-alexandru/web_go_application:${{ github.sha }}
            ghcr.io/clep-alexandru/web_go_application:latest

      - name: Update both rollouts with new image tag
        run: |
          yq -i '.spec.template.spec.containers[0].image = "ghcr.io/clep-alexandru/web_go_application:${{ github.sha }}"' manifests/bluegreen/rollout.yaml
          yq -i '.spec.template.spec.containers[0].image = "ghcr.io/clep-alexandru/web_go_application:${{ github.sha }}"' manifests/ab-testing/rollout.yaml
          yq -i '.spec.template.spec.containers[0].image = "ghcr.io/clep-alexandru/web_go_application:${{ github.sha }}"' manifests/canary/rollout.yaml
          git config user.name "ci-bot"
          git config user.email "ci@github"
          git commit -am "ci: update image tag to ${{ github.sha }}"
          git push

